# Site settings
title: Philipp Alexander Kreer
email: philipp.a.kreer@outlook.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://p-a-kreer.github.io" # the subpath of your site, USE "" for local development
url: https://p-a-kreer.github.io" # the base hostname & protocol for your site, USE "" for local development

twitter_username: philipp-alexander-kreer
github_username: p-a-kreer

# Build settings
markdown: kramdown
